version: '3'

services:
  techmate-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
      - "3300:3300"
    restart: always
    volumes:
      - ./techmate-demo:/app/techmate-demo
